version: 0.2

phases:
  build:
    args:
      - DB_USERNAME=${DB_USERNAME}
      - PASSWORD=${PASSWORD}
    commands:
      - java -version
       - mvn clean package
artifacts:
  files:
    - 'Dockerfile'
    - target/curated-banking-spring-1.0-SNAPSHOT-jar-with-dependencies.jar
