server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update  #create-drop
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    #      database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    # this my person db location
    url: jdbc:postgresql://hika-1.c45c74l14csd.us-east-1.rds.amazonaws.com/postgres?currentSchema=project3

    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  #    url: jdbc:h2:mem:memdb
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password: password
  h2:
    console.enabled: true