server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create  #create-drop #:)
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    #      database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    # this my person db location
    url: jdbc:postgresql://database-1.ccg9vo2amzf1.us-west-1.rds.amazonaws.com/postgres?currentSchema=project3
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: kj&(99cp1X8Rr^yvlL
  #    url: jdbc:h2:mem:memdb
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password: password
  h2:
    console.enabled: true
